
import { Language, InterviewPurpose } from './types';

export const APP_NAME = "TestYoKnowledge";

export const translations = {
  [Language.EN]: {
    appName: APP_NAME,
    welcomeTitle: "Welcome to TestYoKnowledge",
    welcomeDescription: "Sharpen your professional skills with AI-powered voice interviews. Get instant, detailed feedback to ace your next evaluation.",
    startInterview: "Start Interview",
    beginAssessment: "Begin Assessment",
    userInformation: "User Information",
    fillFormPrompt: "Please fill out the form below to begin.",
    fullName: "Full Name",
    fullNamePlaceholder: "e.g., Jane Doe",
    companyName: "Company Name",
    companyNamePlaceholder: "e.g., Acme Corporation",
    positionAppliedFor: "Position Applied For",
    positionAppliedForPlaceholder: "e.g., Senior Software Engineer",
    companyWebsite: "Company Website",
    companyWebsitePlaceholder: "e.g., https://acme.com",
    selectPurpose: "Select Purpose",
    selectLanguage: "Select Interview Language",
    generateQuestions: "Generate Questions",
    interviewScreenTitle: "Interview in Progress",
    question: "Question",
    yourAnswer: "Your Answer:",
    speakNow: "Speak now...",
    processing: "Processing...",
    startAnswering: "Start Answering",
    nextQuestion: "Next Question",
    finishInterview: "Finish Interview",
    generatingReport: "Generating your report...",
    interviewResults: "Interview Results",
    overallPerformance: "Overall Performance",
    hiringDecision: "Hiring Decision",
    strengths: "Strengths",
    weaknesses: "Areas for Improvement",
    recommendations: "Recommendations",
    tryAgain: "Try Another Interview",
    errorOccurred: "An error occurred",
    checkMicPermissions: "Please ensure microphone permissions are granted and try again.",
    errorGeneratingQuestions: "Error Generating Questions",
    errorEvaluating: "Error Evaluating Results",
    unsupportedBrowser: "Your browser does not support speech recognition. Please try Chrome.",
    jobInterview: "Job Interview",
    dailyAssessment: "Daily Employee Assessment",
    trainingEvaluation: "Training Evaluation",
    rwanda: "🇷🇼 Kinyarwanda",
    uk: "🇬🇧 English",
  },
  [Language.RW]: {
    appName: APP_NAME,
    welcomeTitle: "Ikaze kuri TestYoKnowledge",
    welcomeDescription: "Tyaza ubumenyi bwawe mu mwuga ukoresheje ibibazo by'ijwi bya AI. Bona ubugororangingo burambuye kugirango utsinde isuzuma rikurikira.",
    startInterview: "Tangira Ikibazo",
    beginAssessment: "Tangira Isuzuma",
    userInformation: "Amakuru y'ukoresha",
    fillFormPrompt: "Nyamuneka wuzuze uru rubuga hepfo kugirango utangire.",
    fullName: "Amazina Yuzuye",
    fullNamePlaceholder: "urugero, John Ntwali",
    companyName: "Izina ry'ikigo",
    companyNamePlaceholder: "urugero, Ikigo cya Acme",
    positionAppliedFor: "Umwanya usabirwa",
    positionAppliedForPlaceholder: "urugero, Injeniyeri Mukuru wa Porogaramu",
    companyWebsite: "Urubuga rw'ikigo",
    companyWebsitePlaceholder: "urugero, https://acme.com",
    selectPurpose: "Hitamo Intego",
    selectLanguage: "Hitamo Ururimi rw'Ikibazo",
    generateQuestions: "Tanga Ibibazo",
    interviewScreenTitle: "Ikibazo kiri kuba",
    question: "Ikibazo",
    yourAnswer: "Igisubizo cyawe:",
    speakNow: "Vuga ubu...",
    processing: "Birimo gutunganywa...",
    startAnswering: "Tangira Gusubiza",
    nextQuestion: "Ikibazo Gikurikira",
    finishInterview: "Soza Ikibazo",
    generatingReport: "Raporo yawe irimo gukorwa...",
    interviewResults: "Ibisubizo by'Ikibazo",
    overallPerformance: "Imikorere Rusange",
    hiringDecision: "Icyemezo cyo Guhabwa Akazi",
    strengths: "Imbaraga",
    weaknesses: "Ahantu ho kunoza",
    recommendations: "Inama",
    tryAgain: "Gerageza Ikindi Kibazo",
    errorOccurred: "Habaye ikosa",
    checkMicPermissions: "Nyamuneka reba ko wemereye mikoro gukoreshwa hanyuma wongere ugerageze.",
    errorGeneratingQuestions: "Ikosa mu gutanga ibibazo",
    errorEvaluating: "Ikosa mu gusuzuma ibisubizo",
    unsupportedBrowser: "Browser yawe ntishyigikiye ijambo ryandika. Nyamuneka gerageza Chrome.",
    jobInterview: "Ikibazo cy'Akazi",
    dailyAssessment: "Isuzuma rya buri munsi ry'umukozi",
    trainingEvaluation: "Isuzuma ry'amahugurwa",
    rwanda: "🇷🇼 Kinyarwanda",
    uk: "🇬🇧 English",
  }
};

export const purposeOptions = [
    InterviewPurpose.JobInterview,
    InterviewPurpose.DailyAssessment,
    InterviewPurpose.TrainingEvaluation,
];
