
import { Language, InterviewPurpose } from './types';

export const APP_NAME = "TestYoKnowledge";

export const translations = {
  [Language.EN]: {
    appName: APP_NAME,
    welcomeTitle: "Welcome to TestYoKnowledge",
    welcomeDescription: "Sharpen your professional skills with AI-powered voice interviews. Get instant, detailed feedback to ace your next evaluation.",
    startInterview: "Start Interview",
    beginAssessment: "Begin Assessment",
    userInformation: "User Information",
    fillFormPrompt: "Please fill out the form below to begin.",
    fullName: "Full Name",
    fullNamePlaceholder: "e.g., Jane Doe",
    companyName: "Company Name",
    companyNamePlaceholder: "e.g., Acme Corporation",
    positionAppliedFor: "Position Applied For",
    positionAppliedForPlaceholder: "e.g., Senior Software Engineer",
    companyWebsite: "Company Website",
    companyWebsitePlaceholder: "e.g., https://acme.com",
    selectPurpose: "Select Purpose",
    selectLanguage: "Select Interview Language",
    generateQuestions: "Generate Questions",
    interviewScreenTitle: "Interview in Progress",
    question: "Question",
    yourAnswer: "Your Answer:",
    speakNow: "Speak now...",
    processing: "Processing...",
    startAnswering: "Start Answering",
    previousQuestion: "Previous Question",
    nextQuestion: "Next Question",
    finishInterview: "Finish Interview",
    generatingReport: "Generating your report...",
    interviewResults: "Interview Results",
    overallPerformance: "Overall Performance",
    hiringDecision: "Hiring Decision",
    strengths: "Strengths",
    weaknesses: "Areas for Improvement",
    recommendations: "Recommendations",
    tryAgain: "Try Another Interview",
    errorOccurred: "An error occurred",
    checkMicPermissions: "Please ensure microphone permissions are granted and try again.",
    errorGeneratingQuestions: "Error Generating Questions",
    errorEvaluating: "Error Evaluating Results",
    unsupportedBrowser: "Your browser does not support speech recognition. Please try Chrome.",
    jobInterview: "Job Interview",
    dailyAssessment: "Daily Employee Assessment",
    trainingEvaluation: "Training Evaluation",
    jobInterviewDescription: "Simulates a real job interview with questions tailored to the position you're applying for. Aims to assess your qualifications and fit for the role.",
    dailyAssessmentDescription: "A quick daily check-in to assess readiness, mood, and alignment with daily tasks. Useful for team leads and managers.",
    trainingEvaluationDescription: "Evaluates your understanding and retention of material after a training session or module. Helps measure training effectiveness.",
    rwanda: "🇷🇼 Kinyarwanda",
    uk: "🇬🇧 English",
    back: "Back",
    introductionTitle: "Let's Get Started",
    introductionGreeting: "Hello and welcome to your AI-powered job interview. Before we begin, please tell us a little bit about yourself. You can mention your background, education, and work experience. When you're ready, start speaking.",
    yourIntroduction: "Your Introduction",
    startIntroduction: "Start Introduction",
    reRecord: "Re-record",
    continueToInterview: "Continue to Interview",
    stopRecording: "Stop Recording",
    emailReportTitle: "Email Detailed Report",
    emailReportDescription: "Enter your email to receive a full breakdown of your results, including strengths, weaknesses, and recommendations.",
    emailPlaceholder: "Enter your email address",
    sendReport: "Send Report",
    sending: "Sending...",
    reportSentSuccess: "Report sent successfully to",
    invalidEmail: "Please enter a valid email address.",
    previewTitle: "Your Interview Questions",
    previewDescription: "Review your generated questions below. When you're ready, you can proceed to the introduction.",
  },
  [Language.RW]: {
    appName: APP_NAME,
    welcomeTitle: "Ikaze kuri TestYoKnowledge",
    welcomeDescription: "Tyaza ubumenyi bwawe mu mwuga ukoresheje ibibazo by'ijwi bya AI. Bona ubugororangingo burambuye kugirango utsinde isuzuma rikurikira.",
    startInterview: "Tangira Ikibazo",
    beginAssessment: "Tangira Isuzuma",
    userInformation: "Amakuru y'ukoresha",
    fillFormPrompt: "Nyamuneka wuzuze uru rubuga hepfo kugirango utangire.",
    fullName: "Amazina Yuzuye",
    fullNamePlaceholder: "urugero, John Ntwali",
    companyName: "Izina ry'ikigo",
    companyNamePlaceholder: "urugero, Ikigo cya Acme",
    positionAppliedFor: "Umwanya usabirwa",
    positionAppliedForPlaceholder: "urugero, Injeniyeri Mukuru wa Porogaramu",
    companyWebsite: "Urubuga rw'ikigo",
    companyWebsitePlaceholder: "urugero, https://acme.com",
    selectPurpose: "Hitamo Intego",
    selectLanguage: "Hitamo Ururimi rw'Ikibazo",
    generateQuestions: "Tanga Ibibazo",
    interviewScreenTitle: "Ikibazo kiri kuba",
    question: "Ikibazo",
    yourAnswer: "Igisubizo cyawe:",
    speakNow: "Vuga ubu...",
    processing: "Birimo gutunganywa...",
    startAnswering: "Tangira Gusubiza",
    previousQuestion: "Ikibazo Cyabanjirije",
    nextQuestion: "Ikibazo Gikurikira",
    finishInterview: "Soza Ikibazo",
    generatingReport: "Raporo yawe irimo gukorwa...",
    interviewResults: "Ibisubizo by'Ikibazo",
    overallPerformance: "Imikorere Rusange",
    hiringDecision: "Icyemezo cyo Guhabwa Akazi",
    strengths: "Imbaraga",
    weaknesses: "Ahantu ho kunoza",
    recommendations: "Inama",
    tryAgain: "Gerageza Ikindi Kibazo",
    errorOccurred: "Habaye ikosa",
    checkMicPermissions: "Nyamuneka reba ko wemereye mikoro gukoreshwa hanyuma wongere ugerageze.",
    errorGeneratingQuestions: "Ikosa mu gutanga ibibazo",
    errorEvaluating: "Ikosa mu gusuzuma ibisubizo",
    unsupportedBrowser: "Browser yawe ntishyigikiye ijambo ryandika. Nyamuneka gerageza Chrome.",
    jobInterview: "Ikibazo cy'Akazi",
    dailyAssessment: "Isuzuma rya buri munsi ry'umukozi",
    trainingEvaluation: "Isuzuma ry'amahugurwa",
    jobInterviewDescription: "Byigana ikizamini cy'akazi nyacyo n'ibibazo bijyanye n'umwanya usaba. Bigamije gusuzuma ubushobozi bwawe n'uburyo ukwiriye uwo mwanya.",
    dailyAssessmentDescription: "Isuzuma rya buri munsi rigamije kureba imyiteguro, imitekerereze, no guhuza n'inshingano za buri munsi. Ni ingirakamaro ku bayobozi b'amakipe.",
    trainingEvaluationDescription: "Bisuzuma imyumvire yawe n'uburyo wafashe ibikubiye mu mahugurwa. Bifasha gupima ingaruka nziza z'amahugurwa.",
    rwanda: "🇷🇼 Kinyarwanda",
    uk: "🇬🇧 English",
    back: "Inyuma",
    introductionTitle: "Reka Dutangire",
    introductionGreeting: "Muraho kandi ikaze mu kizamini cyanyu cy'akazi cya AI. Mbere yo gutangira, tubwire bike kuri wowe. Ushobora kuvuga amavu n'amavuko yawe, amashuri, n'uburambe mu kazi. Igihe witeguye, tangira kuvuga.",
    yourIntroduction: "Intangiriro Yawe",
    startIntroduction: "Tangira Intangiriro",
    reRecord: "Fata Amajwi Bundi Bushya",
    continueToInterview: "Komeza ku Bibazo",
    stopRecording: "Hagarika Gufata Amajwi",
    emailReportTitle: "Ohereza Raporo Yuzuye",
    emailReportDescription: "Shyiramo imeri yawe kugirango wakire ibisobanuro byuzuye by'ibisubizo byawe, birimo imbaraga, intege nke, n'inama.",
    emailPlaceholder: "Shyiramo imeri yawe",
    sendReport: "Ohereza Raporo",
    sending: "Birimo koherezwa...",
    reportSentSuccess: "Raporo yoherejwe neza kuri",
    invalidEmail: "Nyamuneka shyiramo imeri yemewe.",
    previewTitle: "Ibibazo byawe by'Ikibazo",
    previewDescription: "Soma ibibazo byawe byateguwe hepfo. Igihe witeguye, ushobora gukomeza ku ntangiriro.",
  }
};

export const purposeOptions = [
    InterviewPurpose.JobInterview,
    InterviewPurpose.DailyAssessment,
    InterviewPurpose.TrainingEvaluation,
];

export const purposeDetails = {
    [InterviewPurpose.JobInterview]: {
        key: 'jobInterview',
        descriptionKey: 'jobInterviewDescription'
    },
    [InterviewPurpose.DailyAssessment]: {
        key: 'dailyAssessment',
        descriptionKey: 'dailyAssessmentDescription'
    },
    [InterviewPurpose.TrainingEvaluation]: {
        key: 'trainingEvaluation',
        descriptionKey: 'trainingEvaluationDescription'
    }
} as const;